# Generated by Django 5.0.6 on 2024-06-13 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ('collection 1')
        ""","""
            DELETE FROM store_collection WHERE title='collection 1'
        """)
    ]
